### PR TITLE
PR #7 but branch is now based on the master

### PR DESCRIPTION
**Pull request by sweetcode**
This is exactly the same PR as #7 except that this code is now based on the 'master' branch as it seems this is your active development branch. - I successfully tested it in Firefox (59.0.1) and in Chrome (65.0.3325.181) but Edge didn't work for me at all. I could load the extension but Edge never loaded the extension when I visited the page. 

For details and all commits just check out #7.

### CODE REVIEW

**Comment by dolkensp** [comment]
Ha - yes, I'm a bad person who develops on master occasionally ;)

I'll take a look at this over the weekend.

**Comment by sweetcode** [comment]
Thank you. :) - The CSS may need some work, I admit, it is not my strongest point and most of it is just taken from what I found for the already existing contact search bar.

**Comment by dolkensp** [comment]
That's perfect, as I try to keep the UI built from existing elements.

Was at the Australia vs Colombia football game tonight, but will check tomorrow.

Peter Dolkens

**Comment by sweetcode** [comment]
Any updates? :)

**Comment by dolkensp** [comment]
I've done a bunch on this tonight.

Changed out the search provider, as it was returning some ... interesting results for my hangar.

Fixed minor issue when overlaying the search text over the suggested text (if text was different, or different case, it clashed)

Still want to have a look about better differentiating the suggestion from the search term when the search box doesn't have focus, but then it should be good to go I think.

Will take another look tomorrow - do some cross-browser testing, and go from there. In the meantime, your changes have been merged onto the $/starcitizendotguide/feature/search branch. I've also updated develop to match master, so future pull requests can be pointed at the correct branches.

Cheers
Pete

**Comment by sweetcode** [comment]
Thank you for doing all of the additional work and for merging the PR. :)

~Jan

**Pull request merged**
